### ISSUE TITLE
Er staan fikse fouten in de mark up

### ISSUE THREAD

**Issue by Theo-denBlanken** [SelcukhanK/formulierenhtml1#1]
Dit wordt al gemeld als je de pagina valideert: https://validator.w3.org/nu/?doc=http%3A%2F%2F30229.hosts2.ma-cloud.nl%2Fbewijzenmap%2Fp1.2%2Ffro%2Fformulierenhtml%2Findex.html

**Comment by SelcukhanK** [comment]
deze issues zijn verholpen
